//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.swoop;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.vc.swoop.R.id;
import com.vc.swoop.R.layout;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ADDetailActivity_
    extends ADDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String AD_ID_EXTRA = "ad_id";
    public final static String IN_ACTIVITY_EXTRA = "who";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_addetail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ADDetailActivity_.IntentBuilder_ intent(Context context) {
        return new ADDetailActivity_.IntentBuilder_(context);
    }

    public static ADDetailActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ADDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvBaseRight = ((TextView) hasViews.findViewById(id.tvBaseRight));
        tvBaseTitle = ((TextView) hasViews.findViewById(id.tvBaseTitle));
        btnBaseLeft = ((Button) hasViews.findViewById(id.btnBaseLeft));
        imgBaseLogo = ((ImageView) hasViews.findViewById(id.imgBaseLogo));
        btnBaseRight = ((Button) hasViews.findViewById(id.btnBaseRight));
        llEditPinglun = ((LinearLayout) hasViews.findViewById(id.llEditPinglun));
        ll_relist = ((LinearLayout) hasViews.findViewById(id.ll_relist));
        tv_phone = ((TextView) hasViews.findViewById(id.tv_phone));
        ll_fav = ((LinearLayout) hasViews.findViewById(id.ll_fav));
        tv_content_price = ((TextView) hasViews.findViewById(id.tv_content_price));
        ll_images = ((LinearLayout) hasViews.findViewById(id.ll_images));
        ll_buttons = ((LinearLayout) hasViews.findViewById(id.ll_buttons));
        rel_ad_main = ((RelativeLayout) hasViews.findViewById(id.rel_ad_main));
        ll_content_price = ((LinearLayout) hasViews.findViewById(id.ll_content_price));
        tvComment = ((TextView) hasViews.findViewById(id.tvComment));
        iv_no_ad_default_home = ((ImageView) hasViews.findViewById(id.iv_no_ad_default_home));
        ago_and_id = ((TextView) hasViews.findViewById(id.ago_and_id));
        tvFav = ((TextView) hasViews.findViewById(id.tvFav));
        ad_content = ((TextView) hasViews.findViewById(id.ad_content));
        tv_comment = ((TextView) hasViews.findViewById(id.tv_comment));
        tv_report = ((TextView) hasViews.findViewById(id.tv_report));
        ll_edit = ((LinearLayout) hasViews.findViewById(id.ll_edit));
        ad_title = ((TextView) hasViews.findViewById(id.ad_title));
        tv_price = ((TextView) hasViews.findViewById(id.tv_price));
        iv_logo_item_watch = ((ImageView) hasViews.findViewById(id.iv_logo_item_watch));
        ll_comment = ((LinearLayout) hasViews.findViewById(id.ll_comment));
        tv_distance = ((TextView) hasViews.findViewById(id.tv_distance));
        llCommentPanel = ((LinearLayout) hasViews.findViewById(id.llCommentPanel));
        editContent = ((EditText) hasViews.findViewById(id.editContent));
        if (tvBaseRight!= null) {
            tvBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.rightTextClick();
                }

            }
            );
        }
        if (btnBaseRight!= null) {
            btnBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.rightClick();
                }

            }
            );
        }
        if (btnBaseLeft!= null) {
            btnBaseLeft.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.goBack();
                }

            }
            );
        }
        if (ll_fav!= null) {
            ll_fav.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.ad_remove();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.tvCancel);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.CancelPingLun();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tvclose);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.closePingLun();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.ivCall);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.call();
                    }

                }
                );
            }
        }
        if (tvComment!= null) {
            tvComment.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.ll_comment();
                }

            }
            );
        }
        if (ll_relist!= null) {
            ll_relist.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.btn_relist();
                }

            }
            );
        }
        if (tv_report!= null) {
            tv_report.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.tv_report();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.btn_comment);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.btn_comment();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.tvSend);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.sendPingLun();
                    }

                }
                );
            }
        }
        if (ll_edit!= null) {
            ll_edit.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ADDetailActivity_.this.ad_edit();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.ivMessage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ADDetailActivity_.this.message();
                    }

                }
                );
            }
        }
        InitBase();
        init();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(AD_ID_EXTRA)) {
                ad_id = extras_.getString(AD_ID_EXTRA);
            }
            if (extras_.containsKey(IN_ACTIVITY_EXTRA)) {
                inActivity = extras_.getInt(IN_ACTIVITY_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ADDetailActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ADDetailActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), ADDetailActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

        public ADDetailActivity_.IntentBuilder_ ad_id(String ad_id) {
            return super.extra(AD_ID_EXTRA, ad_id);
        }

        public ADDetailActivity_.IntentBuilder_ inActivity(int inActivity) {
            return super.extra(IN_ACTIVITY_EXTRA, inActivity);
        }

    }

}
