//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.swoop;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.webkit.WebView;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.vc.swoop.R.id;
import com.vc.swoop.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ContentActivity_
    extends ContentActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String ITYPE_EXTRA = "itype";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_content);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ContentActivity_.IntentBuilder_ intent(Context context) {
        return new ContentActivity_.IntentBuilder_(context);
    }

    public static ContentActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ContentActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnBaseRight = ((Button) hasViews.findViewById(id.btnBaseRight));
        btnBaseLeft = ((Button) hasViews.findViewById(id.btnBaseLeft));
        imgBaseLogo = ((ImageView) hasViews.findViewById(id.imgBaseLogo));
        tvBaseRight = ((TextView) hasViews.findViewById(id.tvBaseRight));
        tvBaseTitle = ((TextView) hasViews.findViewById(id.tvBaseTitle));
        webView1 = ((WebView) hasViews.findViewById(id.webView1));
        if (tvBaseRight!= null) {
            tvBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ContentActivity_.this.rightTextClick();
                }

            }
            );
        }
        if (btnBaseLeft!= null) {
            btnBaseLeft.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ContentActivity_.this.goBack();
                }

            }
            );
        }
        if (btnBaseRight!= null) {
            btnBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ContentActivity_.this.rightClick();
                }

            }
            );
        }
        InitBase();
        init();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(ITYPE_EXTRA)) {
                itype = extras_.getString(ITYPE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ContentActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ContentActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), ContentActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

        public ContentActivity_.IntentBuilder_ itype(String itype) {
            return super.extra(ITYPE_EXTRA, itype);
        }

    }

}
