//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.swoop;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.vc.swoop.R.id;
import com.vc.swoop.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ReportActivity_
    extends ReportActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String AD_ID_EXTRA = "ad_id";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_report);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ReportActivity_.IntentBuilder_ intent(Context context) {
        return new ReportActivity_.IntentBuilder_(context);
    }

    public static ReportActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ReportActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvBaseTitle = ((TextView) hasViews.findViewById(id.tvBaseTitle));
        imgBaseLogo = ((ImageView) hasViews.findViewById(id.imgBaseLogo));
        tvBaseRight = ((TextView) hasViews.findViewById(id.tvBaseRight));
        btnBaseLeft = ((Button) hasViews.findViewById(id.btnBaseLeft));
        btnBaseRight = ((Button) hasViews.findViewById(id.btnBaseRight));
        tvReport = ((TextView) hasViews.findViewById(id.tvReport));
        ad_content = ((EditText) hasViews.findViewById(id.ad_content));
        llReport = ((LinearLayout) hasViews.findViewById(id.llReport));
        if (tvBaseRight!= null) {
            tvBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ReportActivity_.this.rightTextClick();
                }

            }
            );
        }
        if (btnBaseRight!= null) {
            btnBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ReportActivity_.this.rightClick();
                }

            }
            );
        }
        if (btnBaseLeft!= null) {
            btnBaseLeft.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ReportActivity_.this.goBack();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ReportActivity_.this.ok();
                    }

                }
                );
            }
        }
        if (llReport!= null) {
            llReport.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ReportActivity_.this.llReport();
                }

            }
            );
        }
        InitBase();
        init();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(AD_ID_EXTRA)) {
                ad_id = extras_.getString(AD_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ReportActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ReportActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), ReportActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

        public ReportActivity_.IntentBuilder_ ad_id(String ad_id) {
            return super.extra(AD_ID_EXTRA, ad_id);
        }

    }

}
