//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.swoop;

import android.content.Context;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.widget.SwipeRefreshLayout;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import com.vc.swoop.R.id;
import com.vc.swoop.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SellingListActivity_
    extends SellingListActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_selling);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SellingListActivity_.IntentBuilder_ intent(Context context) {
        return new SellingListActivity_.IntentBuilder_(context);
    }

    public static SellingListActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new SellingListActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvBaseTitle = ((TextView) hasViews.findViewById(id.tvBaseTitle));
        btnBaseRight = ((Button) hasViews.findViewById(id.btnBaseRight));
        tvBaseRight = ((TextView) hasViews.findViewById(id.tvBaseRight));
        btnBaseLeft = ((Button) hasViews.findViewById(id.btnBaseLeft));
        imgBaseLogo = ((ImageView) hasViews.findViewById(id.imgBaseLogo));
        llEmpty = ((LinearLayout) hasViews.findViewById(id.llEmpty));
        iv_current = ((Button) hasViews.findViewById(id.iv_current));
        iv_expired = ((Button) hasViews.findViewById(id.iv_expired));
        swipeRefreshLayout = ((SwipeRefreshLayout) hasViews.findViewById(id.swipeRefreshLayout));
        ll_segment = ((LinearLayout) hasViews.findViewById(id.ll_segment));
        not_empty = ((FrameLayout) hasViews.findViewById(id.not_empty));
        listview = ((ListView) hasViews.findViewById(id.listview));
        iv_withdrawn = ((Button) hasViews.findViewById(id.iv_withdrawn));
        if (btnBaseRight!= null) {
            btnBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.rightClick();
                }

            }
            );
        }
        if (btnBaseLeft!= null) {
            btnBaseLeft.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.goBack();
                }

            }
            );
        }
        if (tvBaseRight!= null) {
            tvBaseRight.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.rightTextClick();
                }

            }
            );
        }
        if (iv_current!= null) {
            iv_current.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.current();
                }

            }
            );
        }
        if (llEmpty!= null) {
            llEmpty.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.llEmpty();
                }

            }
            );
        }
        if (iv_expired!= null) {
            iv_expired.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.expired();
                }

            }
            );
        }
        if (iv_withdrawn!= null) {
            iv_withdrawn.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SellingListActivity_.this.withdrawn();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.iv_add);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SellingListActivity_.this.iv_add();
                    }

                }
                );
            }
        }
        InitBase();
        init();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<SellingListActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, SellingListActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), SellingListActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

    }

}
